// Code generated by packages/shared/scripts/gen-go-labels.ts. DO NOT EDIT.
//
// Mirrors the translation maps in apps/web/src/lib, which stay the single place
// to edit. Run `bun run gen:go-labels` from packages/shared after changing them;
// CI fails if the two are out of step.

package i18n

// French names for national teams. Clubs keep the API name, so anything absent passes through.
// Source: apps/web/src/lib/teamNames.ts (NATIONAL_TEAM_FR).
var teamFR = map[string]string{
	"Albania":              "Albanie",
	"Algeria":              "Algérie",
	"Andorra":              "Andorre",
	"Argentina":            "Argentine",
	"Armenia":              "Arménie",
	"Australia":            "Australie",
	"Austria":              "Autriche",
	"Azerbaijan":           "Azerbaïdjan",
	"Belarus":              "Biélorussie",
	"Belgium":              "Belgique",
	"Bosnia & Herzegovina": "Bosnie-Herzégovine",
	"Brazil":               "Brésil",
	"Bulgaria":             "Bulgarie",
	"Canada":               "Canada",
	"Cape Verde Islands":   "Cap-Vert",
	"Colombia":             "Colombie",
	"Congo DR":             "RD Congo",
	"Croatia":              "Croatie",
	"Curaçao":              "Curaçao",
	"Cyprus":               "Chypre",
	"Czechia":              "Tchéquie",
	"Denmark":              "Danemark",
	"Ecuador":              "Équateur",
	"Egypt":                "Égypte",
	"England":              "Angleterre",
	"Estonia":              "Estonie",
	"FYR Macedonia":        "Macédoine du Nord",
	"Faroe Islands":        "Îles Féroé",
	"Finland":              "Finlande",
	"France":               "France",
	"Georgia":              "Géorgie",
	"Germany":              "Allemagne",
	"Ghana":                "Ghana",
	"Gibraltar":            "Gibraltar",
	"Greece":               "Grèce",
	"Haiti":                "Haïti",
	"Hungary":              "Hongrie",
	"Iceland":              "Islande",
	"Iran":                 "Iran",
	"Iraq":                 "Irak",
	"Israel":               "Israël",
	"Italy":                "Italie",
	"Ivory Coast":          "Côte d'Ivoire",
	"Japan":                "Japon",
	"Jordan":               "Jordanie",
	"Kazakhstan":           "Kazakhstan",
	"Kosovo":               "Kosovo",
	"Latvia":               "Lettonie",
	"Liechtenstein":        "Liechtenstein",
	"Lithuania":            "Lituanie",
	"Luxembourg":           "Luxembourg",
	"Malta":                "Malte",
	"Mexico":               "Mexique",
	"Moldova":              "Moldavie",
	"Montenegro":           "Monténégro",
	"Morocco":              "Maroc",
	"Netherlands":          "Pays-Bas",
	"New Zealand":          "Nouvelle-Zélande",
	"Northern Ireland":     "Irlande du Nord",
	"Norway":               "Norvège",
	"Panama":               "Panama",
	"Paraguay":             "Paraguay",
	"Poland":               "Pologne",
	"Portugal":             "Portugal",
	"Qatar":                "Qatar",
	"Rep. Of Ireland":      "Irlande",
	"Romania":              "Roumanie",
	"San Marino":           "Saint-Marin",
	"Saudi Arabia":         "Arabie saoudite",
	"Scotland":             "Écosse",
	"Senegal":              "Sénégal",
	"Serbia":               "Serbie",
	"Slovakia":             "Slovaquie",
	"Slovenia":             "Slovénie",
	"South Africa":         "Afrique du Sud",
	"South Korea":          "Corée du Sud",
	"Spain":                "Espagne",
	"Sweden":               "Suède",
	"Switzerland":          "Suisse",
	"Tunisia":              "Tunisie",
	"Türkiye":              "Turquie",
	"USA":                  "États-Unis",
	"Ukraine":              "Ukraine",
	"Uruguay":              "Uruguay",
	"Uzbekistan":           "Ouzbékistan",
	"Wales":                "Pays de Galles",
}

// Competitions French media translate; leagues keep their brand name.
// Source: apps/web/src/lib/labels.ts (COMPETITION_FR).
var competitionFR = map[string]string{
	"World Cup":         "Coupe du Monde",
	"Champions League":  "Ligue des Champions",
	"Europa League":     "Ligue Europa",
	"Conference League": "Ligue Conférence",
	"Nations League":    "Ligue des Nations",
}

// Competition country names.
// Source: apps/web/src/lib/labels.ts (COUNTRY_FR).
var countryFR = map[string]string{
	"France":  "France",
	"England": "Angleterre",
	"Spain":   "Espagne",
	"Germany": "Allemagne",
	"Italy":   "Italie",
	"Europe":  "Europe",
	"World":   "Monde",
}

// Broadcaster coverage notes, as seeded.
// Source: apps/web/src/lib/labels.ts (NOTE_FR).
var noteFR = map[string]string{
	"8 of 9 matches":                      "8 matchs sur 9",
	"Ligue 1 Pass — selected fixtures":    "Pass Ligue 1 — certaines affiches",
	"All of Ligue 2 BKT":                  "Intégralité de la Ligue 2 BKT",
	"Exclusive until 2028":                "Exclusivité jusqu'en 2028",
	"Until 2027":                          "Jusqu'en 2027",
	"Until 2029":                          "Jusqu'en 2029",
	"All matches 2024–27":                 "Intégralité 2024–27",
	"Free-to-air — France matches":        "En clair — matchs de l'équipe de France",
	"All of the Nations League":           "Intégralité de la Ligue des Nations",
	"Free-to-air — France, semis & final": "En clair — France, demies & finale",
	"All 104 matches":                     "Intégralité des 104 matchs",
}
