// Code generated by packages/shared/scripts/gen-go.ts. DO NOT EDIT.
//
// Mirrors the wire contract in packages/shared/src/index.ts, which is the single
// source of truth. Run `bun run gen:go` from packages/shared after changing it;
// CI fails if the two are out of step.

package api

type MatchStatus string

const (
	MatchStatusScheduled MatchStatus = "scheduled"
	MatchStatusLive      MatchStatus = "live"
	MatchStatusFinished  MatchStatus = "finished"
	MatchStatusPostponed MatchStatus = "postponed"
)

type Broadcaster struct {
	ID       int     `json:"id"`
	Slug     string  `json:"slug"`
	Name     string  `json:"name"`
	Color    string  `json:"color"`
	LogoURL  *string `json:"logoUrl"`
	Coverage string  `json:"coverage"`
	Override bool    `json:"override"`
	Note     *string `json:"note"`
}

type MatchEvent struct {
	Type        string  `json:"type"`
	Detail      *string `json:"detail"`
	Minute      *int    `json:"minute"`
	ExtraMinute *int    `json:"extraMinute"`
	Player      *string `json:"player"`
	Assist      *string `json:"assist"`
	Side        *string `json:"side"`
}

type Team struct {
	Name      string  `json:"name"`
	ShortName *string `json:"shortName"`
	Logo      *string `json:"logo"`
}

type Match struct {
	ID            int         `json:"id"`
	Kickoff       string      `json:"kickoff"`
	Status        MatchStatus `json:"status"`
	StatusShort   string      `json:"statusShort"`
	Elapsed       *int        `json:"elapsed"`
	HomeGoals     *int        `json:"homeGoals"`
	AwayGoals     *int        `json:"awayGoals"`
	HomePenalties *int        `json:"homePenalties"`
	AwayPenalties *int        `json:"awayPenalties"`
	Competition   struct {
		Name string `json:"name"`
		Slug string `json:"slug"`
	} `json:"competition"`
	Home         Team          `json:"home"`
	Away         Team          `json:"away"`
	Broadcasters []Broadcaster `json:"broadcasters"`
	Events       []MatchEvent  `json:"events"`
}

type Day struct {
	Key     string  `json:"key"`
	Label   string  `json:"label"`
	Matches []Match `json:"matches"`
}

type LiveMatch struct {
	ID            int         `json:"id"`
	Status        MatchStatus `json:"status"`
	Elapsed       *int        `json:"elapsed"`
	HomeGoals     *int        `json:"homeGoals"`
	AwayGoals     *int        `json:"awayGoals"`
	HomePenalties *int        `json:"homePenalties"`
	AwayPenalties *int        `json:"awayPenalties"`
}

type CompetitionInfo struct {
	Slug    string `json:"slug"`
	Name    string `json:"name"`
	Type    string `json:"type"`
	Country string `json:"country"`
}

// One row of a league/group table.
type StandingRow struct {
	Rank         int     `json:"rank"`
	Team         Team    `json:"team"`
	Played       int     `json:"played"`
	Win          int     `json:"win"`
	Draw         int     `json:"draw"`
	Lose         int     `json:"lose"`
	GoalsFor     int     `json:"goalsFor"`
	GoalsAgainst int     `json:"goalsAgainst"`
	GoalsDiff    int     `json:"goalsDiff"`
	Points       int     `json:"points"`
	Form         *string `json:"form"`
	Description  *string `json:"description"`
}

// A single table. Leagues have one group ("Overall"); cups can have many.
type StandingGroup struct {
	Label string        `json:"label"`
	Rows  []StandingRow `json:"rows"`
}

// One knockout tie in a bracket (teams are null until the fixture is drawn).
type BracketMatch struct {
	ID            int         `json:"id"`
	Kickoff       string      `json:"kickoff"`
	Status        MatchStatus `json:"status"`
	Home          *Team       `json:"home"`
	Away          *Team       `json:"away"`
	HomeGoals     *int        `json:"homeGoals"`
	AwayGoals     *int        `json:"awayGoals"`
	HomePenalties *int        `json:"homePenalties"`
	AwayPenalties *int        `json:"awayPenalties"`
	Winner        *string     `json:"winner"`
}

// One column of the bracket (all ties of a knockout round).
type BracketRound struct {
	Name    string         `json:"name"`
	Matches []BracketMatch `json:"matches"`
}

// The competition page payload: its tables and/or knockout bracket.
// One row of a top-scorers / top-assists ranking. `value` = goals or assists.
type TopPlayerEntry struct {
	Rank   int    `json:"rank"`
	Player string `json:"player"`
	Team   string `json:"team"`
	Value  int    `json:"value"`
}

type CompetitionDetail struct {
	Slug       string           `json:"slug"`
	Name       string           `json:"name"`
	Type       string           `json:"type"`
	Country    string           `json:"country"`
	Standings  []StandingGroup  `json:"standings"`
	Bracket    []BracketRound   `json:"bracket"`
	TopScorers []TopPlayerEntry `json:"topScorers"`
	TopAssists []TopPlayerEntry `json:"topAssists"`
}

type LineupPlayer struct {
	Name   string   `json:"name"`
	Number *int     `json:"number"`
	Pos    *string  `json:"pos"`
	Grid   *string  `json:"grid"`
	Rating *float64 `json:"rating"`
}

type TeamLineup struct {
	Formation   *string        `json:"formation"`
	Coach       *string        `json:"coach"`
	StartXI     []LineupPlayer `json:"startXI"`
	Substitutes []LineupPlayer `json:"substitutes"`
}

type MatchLineups struct {
	Home TeamLineup `json:"home"`
	Away TeamLineup `json:"away"`
}

// A curated set of team match statistics; any field may be null (hidden).
type TeamStats struct {
	Possession      *int     `json:"possession"`
	Shots           *int     `json:"shots"`
	ShotsOnTarget   *int     `json:"shotsOnTarget"`
	ShotsOffTarget  *int     `json:"shotsOffTarget"`
	BlockedShots    *int     `json:"blockedShots"`
	ShotsInsideBox  *int     `json:"shotsInsideBox"`
	ShotsOutsideBox *int     `json:"shotsOutsideBox"`
	XG              *float64 `json:"xg"`
	Corners         *int     `json:"corners"`
	Fouls           *int     `json:"fouls"`
	Offsides        *int     `json:"offsides"`
	Saves           *int     `json:"saves"`
	GoalsPrevented  *float64 `json:"goalsPrevented"`
	PassAccuracy    *int     `json:"passAccuracy"`
	YellowCards     *int     `json:"yellowCards"`
	RedCards        *int     `json:"redCards"`
}

type MatchStatistics struct {
	Home TeamStats `json:"home"`
	Away TeamStats `json:"away"`
}

// A single match with the extra fields worth showing on its detail page.
// Pre-match prediction: win probabilities (0–100) + the API's one-line advice.
type MatchPrediction struct {
	Home   int     `json:"home"`
	Draw   int     `json:"draw"`
	Away   int     `json:"away"`
	Advice *string `json:"advice"`
}

// Man of the match: the top-rated player.
type MatchMotm struct {
	Name   string  `json:"name"`
	Side   string  `json:"side"`
	Rating float64 `json:"rating"`
}

type MatchDetail struct {
	Match
	Venue       *string          `json:"venue"`
	Round       *string          `json:"round"`
	Referee     *string          `json:"referee"`
	Lineups     *MatchLineups    `json:"lineups"`
	Statistics  *MatchStatistics `json:"statistics"`
	Predictions *MatchPrediction `json:"predictions"`
	Motm        *MatchMotm       `json:"motm"`
}

// One scheduled-job outcome, as surfaced by the logs page. `at` is an ISO
// string; `detail` is the job's result object (or `{ err }` on failure).
type RunLogEntry struct {
	ID     int            `json:"id"`
	At     string         `json:"at"`
	Job    string         `json:"job"`
	Ok     bool           `json:"ok"`
	Detail map[string]any `json:"detail"`
	Ms     *int           `json:"ms"`
}

// A pickable team for the "My teams" search (no fixtures attached).
type TeamOption struct {
	Name      string  `json:"name"`
	ShortName *string `json:"shortName"`
}

// Response bodies.
type ScheduleResponse struct {
	Days []Day `json:"days"`
}

type TeamsResponse struct {
	Teams []TeamOption `json:"teams"`
}

type MatchDetailResponse struct {
	Match *MatchDetail `json:"match"`
}

type LiveResponse struct {
	Matches []LiveMatch `json:"matches"`
}

type CompetitionsResponse struct {
	Competitions []CompetitionInfo `json:"competitions"`
}

type CompetitionDetailResponse struct {
	Competition *CompetitionDetail `json:"competition"`
}

type LogsResponse struct {
	Ok   bool          `json:"ok"`
	Runs []RunLogEntry `json:"runs"`
}

// This device's explicit surveillance ("radar") decisions: `on` = watch, `off` =
// mute (overrides a followed team). A match in neither is at its default (auto-
// surveilled iff a followed team plays — the client resolves that from its follows).
type WatchListResponse struct {
	On  []int `json:"on"`
	Off []int `json:"off"`
}
