/**
 * Generates the Go label tables from the web client's translation maps.
 *
 *   bun run gen:go-labels
 *
 * The maps live in apps/web/src/lib because that is where they were written;
 * copying them into Go by hand would drift the moment a team name is corrected
 * in one client and not the other. CI regenerates and fails on any diff, so
 * there is still exactly one place to edit.
 *
 * Only the data is generated. roundLabel's logic is pattern-matching rather than
 * a table, so it is hand-ported and lives in labels.go.
 */
import ts from "typescript";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";

const WEB_LIB = join(import.meta.dir, "..", "..", "..", "apps", "web", "src", "lib");
const OUT = join(import.meta.dir, "..", "..", "..", "apps", "tui", "internal", "i18n", "labels_gen.go");

/** Which map in which file becomes which Go identifier. */
const TABLES = [
  { file: "teamNames.ts", constName: "NATIONAL_TEAM_FR", goName: "teamFR", doc: "French names for national teams. Clubs keep the API name, so anything absent passes through." },
  { file: "labels.ts", constName: "COMPETITION_FR", goName: "competitionFR", doc: "Competitions French media translate; leagues keep their brand name." },
  { file: "labels.ts", constName: "COUNTRY_FR", goName: "countryFR", doc: "Competition country names." },
  { file: "labels.ts", constName: "NOTE_FR", goName: "noteFR", doc: "Broadcaster coverage notes, as seeded." },
];

/** Pull one `const X: Record<string,string> = { … }` out of a source file. */
async function extract(file: string, constName: string): Promise<[string, string][]> {
  const path = join(WEB_LIB, file);
  const src = ts.createSourceFile(path, await Bun.file(path).text(), ts.ScriptTarget.Latest, true);

  let found: [string, string][] | null = null;
  const visit = (node: ts.Node): void => {
    if (
      ts.isVariableDeclaration(node) &&
      ts.isIdentifier(node.name) &&
      node.name.text === constName &&
      node.initializer &&
      ts.isObjectLiteralExpression(node.initializer)
    ) {
      found = node.initializer.properties.flatMap((p) => {
        if (!ts.isPropertyAssignment(p)) return [];
        const key = ts.isStringLiteral(p.name) || ts.isIdentifier(p.name) ? p.name.text : null;
        const val = ts.isStringLiteral(p.initializer) ? p.initializer.text : null;
        return key !== null && val !== null ? [[key, val] as [string, string]] : [];
      });
    }
    ts.forEachChild(node, visit);
  };
  visit(src);

  if (found === null) throw new Error(`${constName} not found in ${file}`);
  const entries = found as [string, string][];
  if (entries.length === 0) throw new Error(`${constName} in ${file} produced no entries`);
  return entries;
}

const parts = [
  `// Code generated by packages/shared/scripts/gen-go-labels.ts. DO NOT EDIT.
//
// Mirrors the translation maps in apps/web/src/lib, which stay the single place
// to edit. Run \`bun run gen:go-labels\` from packages/shared after changing them;
// CI fails if the two are out of step.

package i18n
`,
];

for (const t of TABLES) {
  const entries = await extract(t.file, t.constName);
  const rows = entries
    .map(([k, v]) => `\t${JSON.stringify(k)}: ${JSON.stringify(v)},`)
    .join("\n");
  parts.push(`// ${t.doc}\n// Source: apps/web/src/lib/${t.file} (${t.constName}).\nvar ${t.goName} = map[string]string{\n${rows}\n}\n`);
  console.log(`${t.goName}: ${entries.length} entries`);
}

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, parts.join("\n"));

// gofmt here, not afterwards: unformatted output would differ from the
// committed file on every run and make the CI drift check fail for the wrong
// reason.
const fmt = Bun.spawnSync(["gofmt", "-w", OUT]);
if (!fmt.success) {
  console.error(new TextDecoder().decode(fmt.stderr));
  throw new Error("gofmt failed on the generated file");
}
console.log(`wrote ${OUT}`);
