import type { Lang } from "./settings";

/** French names for national teams (World Cup + Nations League). Clubs keep the
 *  API name in both languages, so anything not here passes through unchanged. */
const NATIONAL_TEAM_FR: Record<string, string> = {
  Albania: "Albanie",
  Algeria: "Algérie",
  Andorra: "Andorre",
  Argentina: "Argentine",
  Armenia: "Arménie",
  Australia: "Australie",
  Austria: "Autriche",
  Azerbaijan: "Azerbaïdjan",
  Belarus: "Biélorussie",
  Belgium: "Belgique",
  "Bosnia & Herzegovina": "Bosnie-Herzégovine",
  Brazil: "Brésil",
  Bulgaria: "Bulgarie",
  Canada: "Canada",
  "Cape Verde Islands": "Cap-Vert",
  Colombia: "Colombie",
  "Congo DR": "RD Congo",
  Croatia: "Croatie",
  Curaçao: "Curaçao",
  Cyprus: "Chypre",
  Czechia: "Tchéquie",
  Denmark: "Danemark",
  Ecuador: "Équateur",
  Egypt: "Égypte",
  England: "Angleterre",
  Estonia: "Estonie",
  "FYR Macedonia": "Macédoine du Nord",
  "Faroe Islands": "Îles Féroé",
  Finland: "Finlande",
  France: "France",
  Georgia: "Géorgie",
  Germany: "Allemagne",
  Ghana: "Ghana",
  Gibraltar: "Gibraltar",
  Greece: "Grèce",
  Haiti: "Haïti",
  Hungary: "Hongrie",
  Iceland: "Islande",
  Iran: "Iran",
  Iraq: "Irak",
  Israel: "Israël",
  Italy: "Italie",
  "Ivory Coast": "Côte d'Ivoire",
  Japan: "Japon",
  Jordan: "Jordanie",
  Kazakhstan: "Kazakhstan",
  Kosovo: "Kosovo",
  Latvia: "Lettonie",
  Liechtenstein: "Liechtenstein",
  Lithuania: "Lituanie",
  Luxembourg: "Luxembourg",
  Malta: "Malte",
  Mexico: "Mexique",
  Moldova: "Moldavie",
  Montenegro: "Monténégro",
  Morocco: "Maroc",
  Netherlands: "Pays-Bas",
  "New Zealand": "Nouvelle-Zélande",
  "Northern Ireland": "Irlande du Nord",
  Norway: "Norvège",
  Panama: "Panama",
  Paraguay: "Paraguay",
  Poland: "Pologne",
  Portugal: "Portugal",
  Qatar: "Qatar",
  "Rep. Of Ireland": "Irlande",
  Romania: "Roumanie",
  "San Marino": "Saint-Marin",
  "Saudi Arabia": "Arabie saoudite",
  Scotland: "Écosse",
  Senegal: "Sénégal",
  Serbia: "Serbie",
  Slovakia: "Slovaquie",
  Slovenia: "Slovénie",
  "South Africa": "Afrique du Sud",
  "South Korea": "Corée du Sud",
  Spain: "Espagne",
  Sweden: "Suède",
  Switzerland: "Suisse",
  Tunisia: "Tunisie",
  Türkiye: "Turquie",
  USA: "États-Unis",
  Ukraine: "Ukraine",
  Uruguay: "Uruguay",
  Uzbekistan: "Ouzbékistan",
  Wales: "Pays de Galles",
};

/** Real club names — API-Football gives short/city forms for many French clubs
 *  ("Lyon", "Lens", "Lille"). These override the display in BOTH languages (club
 *  names aren't translated), and also make the full name searchable. Keyed by the
 *  exact API name. Scope: Ligue 1 + Ligue 2. */
const CLUB_NAMES: Record<string, string> = {
  // Ligue 1
  Angers: "Angers SCO",
  Auxerre: "AJ Auxerre",
  "Estac Troyes": "ESTAC Troyes",
  "Le Havre": "Le Havre AC",
  "Le Mans": "Le Mans FC",
  Lens: "RC Lens",
  Lille: "LOSC Lille",
  Lorient: "FC Lorient",
  Lyon: "Olympique Lyonnais",
  Marseille: "Olympique de Marseille",
  Monaco: "AS Monaco",
  Nice: "OGC Nice",
  "Paris Saint Germain": "Paris Saint-Germain",
  Rennes: "Stade Rennais",
  Strasbourg: "RC Strasbourg",
  Toulouse: "Toulouse FC",
  // Ligue 2
  Annecy: "FC Annecy",
  Boulogne: "US Boulogne",
  "Clermont Foot": "Clermont Foot 63",
  Dijon: "Dijon FCO",
  Dunkerque: "USL Dunkerque",
  Grenoble: "Grenoble Foot 38",
  Guingamp: "EA Guingamp",
  Laval: "Stade Lavallois",
  Metz: "FC Metz",
  Montpellier: "Montpellier HSC",
  Nancy: "AS Nancy Lorraine",
  Nantes: "FC Nantes",
  PAU: "Pau FC",
  "RED Star FC 93": "Red Star FC",
  Reims: "Stade de Reims",
  Rodez: "Rodez AF",
  "Saint Etienne": "AS Saint-Étienne",
  Sochaux: "FC Sochaux-Montbéliard",
};

/** Localise a team name — real club name if known (both languages), else national
 *  teams to French, else the API name unchanged. */
export function teamName(name: string, lang: Lang): string {
  const club = CLUB_NAMES[name];
  if (club) return club;
  return lang === "fr" ? (NATIONAL_TEAM_FR[name] ?? name) : name;
}
