import type { Lang } from "./settings";

/** French names for national teams (World Cup + Nations League). Clubs keep the
 *  API name in both languages, so anything not here passes through unchanged. */
const NATIONAL_TEAM_FR: Record<string, string> = {
  Albania: "Albanie",
  Algeria: "Algérie",
  Andorra: "Andorre",
  Argentina: "Argentine",
  Armenia: "Arménie",
  Australia: "Australie",
  Austria: "Autriche",
  Azerbaijan: "Azerbaïdjan",
  Belarus: "Biélorussie",
  Belgium: "Belgique",
  "Bosnia & Herzegovina": "Bosnie-Herzégovine",
  Brazil: "Brésil",
  Bulgaria: "Bulgarie",
  Canada: "Canada",
  "Cape Verde Islands": "Cap-Vert",
  Colombia: "Colombie",
  "Congo DR": "RD Congo",
  Croatia: "Croatie",
  Curaçao: "Curaçao",
  Cyprus: "Chypre",
  Czechia: "Tchéquie",
  Denmark: "Danemark",
  Ecuador: "Équateur",
  Egypt: "Égypte",
  England: "Angleterre",
  Estonia: "Estonie",
  "FYR Macedonia": "Macédoine du Nord",
  "Faroe Islands": "Îles Féroé",
  Finland: "Finlande",
  France: "France",
  Georgia: "Géorgie",
  Germany: "Allemagne",
  Ghana: "Ghana",
  Gibraltar: "Gibraltar",
  Greece: "Grèce",
  Haiti: "Haïti",
  Hungary: "Hongrie",
  Iceland: "Islande",
  Iran: "Iran",
  Iraq: "Irak",
  Israel: "Israël",
  Italy: "Italie",
  "Ivory Coast": "Côte d'Ivoire",
  Japan: "Japon",
  Jordan: "Jordanie",
  Kazakhstan: "Kazakhstan",
  Kosovo: "Kosovo",
  Latvia: "Lettonie",
  Liechtenstein: "Liechtenstein",
  Lithuania: "Lituanie",
  Luxembourg: "Luxembourg",
  Malta: "Malte",
  Mexico: "Mexique",
  Moldova: "Moldavie",
  Montenegro: "Monténégro",
  Morocco: "Maroc",
  Netherlands: "Pays-Bas",
  "New Zealand": "Nouvelle-Zélande",
  "Northern Ireland": "Irlande du Nord",
  Norway: "Norvège",
  Panama: "Panama",
  Paraguay: "Paraguay",
  Poland: "Pologne",
  Portugal: "Portugal",
  Qatar: "Qatar",
  "Rep. Of Ireland": "Irlande",
  Romania: "Roumanie",
  "San Marino": "Saint-Marin",
  "Saudi Arabia": "Arabie saoudite",
  Scotland: "Écosse",
  Senegal: "Sénégal",
  Serbia: "Serbie",
  Slovakia: "Slovaquie",
  Slovenia: "Slovénie",
  "South Africa": "Afrique du Sud",
  "South Korea": "Corée du Sud",
  Spain: "Espagne",
  Sweden: "Suède",
  Switzerland: "Suisse",
  Tunisia: "Tunisie",
  Türkiye: "Turquie",
  USA: "États-Unis",
  Ukraine: "Ukraine",
  Uruguay: "Uruguay",
  Uzbekistan: "Ouzbékistan",
  Wales: "Pays de Galles",
};

/** Localise a team name — national teams to French, clubs unchanged. */
export function teamName(name: string, lang: Lang): string {
  return lang === "fr" ? (NATIONAL_TEAM_FR[name] ?? name) : name;
}
